### PR TITLE
Allow "UNPROTECTED" to be set for the "Do Not Protect" SLA domain...

### PR DESCRIPTION
**Pull request by bender-the-greatest**
… and make sure that the SLA Domain name passed in resolves a valid SLA Domain ID

# Description
Allow UNPROTECTED to be passed in as the SLA Domain name, and error out if the provided SLA domain name does not exist.

## Related Issue

#11 

## Motivation and Context

Currently you cannot set "Do Not Protect" with this plugin via any means I could locate. Also passing in an SLA domain name that does not exist results in an infinite loop until the workflow is cancelled.

## How Has This Been Tested?

This has been validated in our vRealize environment during automated deployments of virtual machines. A manual test with an invalid SLA domain name was used to trigger the failure to resolve the SLA ID path.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply. If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [x] My code follows the code style of this project (as far as I can tell it does)
- [x] My change requires a change to the documentation (I didn't see any relevant documentation for this plugin going over Do Not Protect)
- [x] I have updated the documentation accordingly. (See above)
- [x] I have read the **[CONTRIBUTION](https://github.com/rubrikinc/rubrik-plugin-for-vrealize/blob/master/CONTRIBUTING.md)** document.
- [x] I have updated the CHANGELOG file accordingly for the version that this merge modifies (What changelog file?)
- [x] I have added tests to cover my changes (vRO doesn't really allow for unit testing in the traditional sense, but I did test this change)
- [x] All new and existing tests passed (I tested with valid SLA domain names, the UNPROTECTED special case for "Do Not Protect", and nonexistant SLA domain names for failing on a nonexistant SLA domain.

### CODE REVIEW

**Comment by bender-the-greatest** [comment]
I just realized this is sourced from a copy of the packagye from 4/8, but was last updated on 5/22. Let me update our plugin and redo this change and I'll update my master branch.

**Comment by rfitzhugh** [comment]
Hi @bender-the-greatest - is this PR ready for review?

**Comment by bender-the-greatest** [comment]
@rfitzhugh Sorry, I got pulled into something else and haven't had the time to update our version of the plugin and see if my changes work with the latest.

**Comment by rfitzhugh** [comment]
Closing due to inactivity. Please re-open if PR is ready for review.

**Pull request closed without merging**
